# Generated by Django 2.0.5 on 2021-05-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=200)),
                ('departmentLocation', models.CharField(max_length=200)),
                ('departmentNumber', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
                ('dateJoin', models.DateField()),
            ],
        ),
    ]
