# Generated by Django 3.1.7 on 2021-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phoneNum', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=200)),
                ('jobCategory', models.CharField(max_length=200)),
                ('jobDescription', models.TextField()),
                ('jobRequirements', models.TextField()),
                ('salary', models.CharField(max_length=200)),
                ('jobNature', models.CharField(max_length=200)),
                ('jobExperience', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('companyEmail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HirerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phoneNum', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('letter', models.TextField()),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobfinder.hirer')),
            ],
        ),
    ]
